/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static void main(String[] args) {
        String someNumber = "01012018";
        System.out.println(someNumber.length());
    }
}
